"""
info_app.py — displays build metadata injected by the pre-build hook.
Packaged in Example 09 to demonstrate hook_pre / hook_post.
"""

import sys

# build_info.py is generated by the pre-build hook in build.py
try:
    import build_info
    TIMESTAMP = build_info.BUILD_TIMESTAMP
    BUILD_NUM = build_info.BUILD_NUMBER
    BUILDER   = build_info.BUILT_BY
except ImportError:
    TIMESTAMP = "unknown (running from source)"
    BUILD_NUM = 0
    BUILDER   = "unknown"


def main() -> None:
    print("=" * 50)
    print("  InfoApp")
    print("=" * 50)
    print(f"  Build number    : {BUILD_NUM}")
    print(f"  Build timestamp : {TIMESTAMP}")
    print(f"  Built by        : {BUILDER}")
    print(f"  Python          : {sys.version.split()[0]}")
    print("=" * 50)
    input("\nPress Enter to exit...")


if __name__ == "__main__":
    main()
